/*

-- Cliente de SP
        -- 1. Definir variables de salida
        SET @P_CODIGO = '';
        SET @P_DESCRIPCION = '';

        -- 2. Llamar al procedimiento
        CALL SP_PROCESAR_CLASIFICADO_DETALLE(
            '20251228_135938.jpg',  -- P_ID_CLASIFICADO
            @P_CODIGO,
            @P_DESCRIPCION
        );

        -- 3. Ver resultados
        SELECT @P_CODIGO AS CODIGO, @P_DESCRIPCION AS DESCRIPCION;

*/

DELIMITER $$

CREATE PROCEDURE SP_PROCESAR_CLASIFICADO_DETALLE(
    IN  P_ID_CLASIFICADO VARCHAR(50),
    OUT P_CODIGO         VARCHAR(20),
    OUT P_DESCRIPCION    VARCHAR(500)
)
proc:BEGIN
    DECLARE V_SUMA_ROYAL      DECIMAL(14,4) DEFAULT 0.0000;
    DECLARE V_SUMA_BL         DECIMAL(14,4) DEFAULT 0.0000;
    DECLARE V_SUMA_FS         DECIMAL(14,4) DEFAULT 0.0000;
    DECLARE V_SUMA_HZ         DECIMAL(14,4) DEFAULT 0.0000;
    DECLARE V_SUMA_SURI       DECIMAL(14,4) DEFAULT 0.0000;
    DECLARE V_SUMA_SURI_HZ    DECIMAL(14,4) DEFAULT 0.0000;

    DECLARE V_SUMA_IMPORTE_TOTAL DECIMAL(14,4) DEFAULT 0.0000;
    DECLARE V_SUBTOTAL_IMPORTE   DECIMAL(14,4) DEFAULT 0.0000;

    DECLARE V_PRECIO_ROYAL    DECIMAL(14,4) DEFAULT 1.1000;
    DECLARE V_PRECIO_BL       DECIMAL(14,4) DEFAULT 0.8000;
    DECLARE V_PRECIO_FS       DECIMAL(14,4) DEFAULT 0.7000;
    DECLARE V_PRECIO_HZ       DECIMAL(14,4) DEFAULT 0.3000;
    DECLARE V_PRECIO_SURI     DECIMAL(14,4) DEFAULT 0.6000;
    DECLARE V_PRECIO_SURI_HZ  DECIMAL(14,4) DEFAULT 0.3000;

    DECLARE V_CLASIFICADO_EXISTS INT DEFAULT 0;
    DECLARE V_PESO_AG           DECIMAL(14,4) DEFAULT 0.0000;
    DECLARE V_SUMA_HZ_BASE      DECIMAL(14,4) DEFAULT 0.0000;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SET P_CODIGO = 'ERROR';
        SET P_DESCRIPCION = 'Error al procesar el clasificado. Operación cancelada.';
    END;

    START TRANSACTION;

    SELECT COUNT(*) INTO V_CLASIFICADO_EXISTS
    FROM CLASIFICADO
    WHERE ID_CLASIFICADO = P_ID_CLASIFICADO;

    IF V_CLASIFICADO_EXISTS = 0 THEN
        SET P_CODIGO = 'ERROR';
        SET P_DESCRIPCION = CONCAT('El clasificado [', P_ID_CLASIFICADO, '] no existe.');
        ROLLBACK;
        LEAVE proc;
    END IF;

    -- (Opcional recomendado si hay concurrencia)
    -- SELECT ID_CLASIFICADO FROM CLASIFICADO
    -- WHERE ID_CLASIFICADO = P_ID_CLASIFICADO
    -- FOR UPDATE;

    DELETE FROM CLASIFICADO_DETALLE
    WHERE ID_CLASIFICADO = P_ID_CLASIFICADO;

    -- 1) ROYAL
    SELECT COALESCE(SUM(PESO_KG),0) INTO V_SUMA_ROYAL
    FROM CLASIFICADO_PESO
    WHERE ID_CALIDAD='ROYAL' AND ID_CLASIFICADO=P_ID_CLASIFICADO;

    IF V_SUMA_ROYAL > 0 THEN
        SET V_SUBTOTAL_IMPORTE = V_SUMA_ROYAL * V_PRECIO_ROYAL;

        INSERT INTO CLASIFICADO_DETALLE(ID_CLASIFICADO,ID_AGRUPACION,TOTAL_KG,PRECIO_KG,SUBTOTAL_IMPORTE)
        VALUES (P_ID_CLASIFICADO,'ROYAL',ROUND(V_SUMA_ROYAL,2),ROUND(V_PRECIO_ROYAL,2),ROUND(V_SUBTOTAL_IMPORTE,2));

        SET V_SUMA_IMPORTE_TOTAL = V_SUMA_IMPORTE_TOTAL + V_SUBTOTAL_IMPORTE;
    END IF;

    -- 2) BL
    SELECT COALESCE(SUM(PESO_KG),0) INTO V_SUMA_BL
    FROM CLASIFICADO_PESO
    WHERE ID_CALIDAD IN ('STD','BL-B','BL-X') AND ID_CLASIFICADO=P_ID_CLASIFICADO;

    IF V_SUMA_BL > 0 THEN
        SET V_SUBTOTAL_IMPORTE = V_SUMA_BL * V_PRECIO_BL;

        INSERT INTO CLASIFICADO_DETALLE(ID_CLASIFICADO,ID_AGRUPACION,TOTAL_KG,PRECIO_KG,SUBTOTAL_IMPORTE)
        VALUES (P_ID_CLASIFICADO,'BL',ROUND(V_SUMA_BL,2),ROUND(V_PRECIO_BL,2),ROUND(V_SUBTOTAL_IMPORTE,2));

        SET V_SUMA_IMPORTE_TOTAL = V_SUMA_IMPORTE_TOTAL + V_SUBTOTAL_IMPORTE;
    END IF;

    -- 3) FS
    SELECT COALESCE(SUM(PESO_KG),0) INTO V_SUMA_FS
    FROM CLASIFICADO_PESO
    WHERE ID_CALIDAD IN ('FS-B','FS-X') AND ID_CLASIFICADO=P_ID_CLASIFICADO;

    IF V_SUMA_FS > 0 THEN
        SET V_SUBTOTAL_IMPORTE = V_SUMA_FS * V_PRECIO_FS;

        INSERT INTO CLASIFICADO_DETALLE(ID_CLASIFICADO,ID_AGRUPACION,TOTAL_KG,PRECIO_KG,SUBTOTAL_IMPORTE)
        VALUES (P_ID_CLASIFICADO,'FS',ROUND(V_SUMA_FS,2),ROUND(V_PRECIO_FS,2),ROUND(V_SUBTOTAL_IMPORTE,2));

        SET V_SUMA_IMPORTE_TOTAL = V_SUMA_IMPORTE_TOTAL + V_SUBTOTAL_IMPORTE;
    END IF;

    -- 4) HZ = (HZ-B + HZ-X + AG)
    SELECT COALESCE(SUM(PESO_KG),0) INTO V_PESO_AG
    FROM CLASIFICADO_PESO
    WHERE ID_CALIDAD='AG' AND ID_CLASIFICADO=P_ID_CLASIFICADO;

    SELECT COALESCE(SUM(PESO_KG),0) INTO V_SUMA_HZ_BASE
    FROM CLASIFICADO_PESO
    WHERE ID_CALIDAD IN ('HZ-B','HZ-X') AND ID_CLASIFICADO=P_ID_CLASIFICADO;

    SET V_SUMA_HZ = V_SUMA_HZ_BASE + V_PESO_AG;

    IF V_SUMA_HZ > 0 THEN
        SET V_SUBTOTAL_IMPORTE = V_SUMA_HZ * V_PRECIO_HZ;

        INSERT INTO CLASIFICADO_DETALLE(ID_CLASIFICADO,ID_AGRUPACION,TOTAL_KG,PRECIO_KG,SUBTOTAL_IMPORTE)
        VALUES (P_ID_CLASIFICADO,'HZ',ROUND(V_SUMA_HZ,2),ROUND(V_PRECIO_HZ,2),ROUND(V_SUBTOTAL_IMPORTE,2));

        SET V_SUMA_IMPORTE_TOTAL = V_SUMA_IMPORTE_TOTAL + V_SUBTOTAL_IMPORTE;
    END IF;

    -- 5) SURI
    SELECT COALESCE(SUM(PESO_KG),0) INTO V_SUMA_SURI
    FROM CLASIFICADO_PESO
    WHERE ID_CALIDAD IN ('SURI-BL','SURI-FS') AND ID_CLASIFICADO=P_ID_CLASIFICADO;

    IF V_SUMA_SURI > 0 THEN
        SET V_SUBTOTAL_IMPORTE = V_SUMA_SURI * V_PRECIO_SURI;

        INSERT INTO CLASIFICADO_DETALLE(ID_CLASIFICADO,ID_AGRUPACION,TOTAL_KG,PRECIO_KG,SUBTOTAL_IMPORTE)
        VALUES (P_ID_CLASIFICADO,'SURI',ROUND(V_SUMA_SURI,2),ROUND(V_PRECIO_SURI,2),ROUND(V_SUBTOTAL_IMPORTE,2));

        SET V_SUMA_IMPORTE_TOTAL = V_SUMA_IMPORTE_TOTAL + V_SUBTOTAL_IMPORTE;
    END IF;

    -- 6) SURI-HZ
    SELECT COALESCE(SUM(PESO_KG),0) INTO V_SUMA_SURI_HZ
    FROM CLASIFICADO_PESO
    WHERE ID_CALIDAD='SURI-HZ' AND ID_CLASIFICADO=P_ID_CLASIFICADO;

    IF V_SUMA_SURI_HZ > 0 THEN
        SET V_SUBTOTAL_IMPORTE = V_SUMA_SURI_HZ * V_PRECIO_SURI_HZ;

        INSERT INTO CLASIFICADO_DETALLE(ID_CLASIFICADO,ID_AGRUPACION,TOTAL_KG,PRECIO_KG,SUBTOTAL_IMPORTE)
        VALUES (P_ID_CLASIFICADO,'SURI-HZ',ROUND(V_SUMA_SURI_HZ,2),ROUND(V_PRECIO_SURI_HZ,2),ROUND(V_SUBTOTAL_IMPORTE,2));

        SET V_SUMA_IMPORTE_TOTAL = V_SUMA_IMPORTE_TOTAL + V_SUBTOTAL_IMPORTE;
    END IF;

    UPDATE CLASIFICADO
    SET IMPORTE_TOTAL = ROUND(V_SUMA_IMPORTE_TOTAL, 2)
    WHERE ID_CLASIFICADO = P_ID_CLASIFICADO;

    COMMIT;

    SET P_CODIGO = 'OK';
    SET P_DESCRIPCION = CONCAT('Clasificado procesado exitosamente. Importe total: ', CAST(ROUND(V_SUMA_IMPORTE_TOTAL,2) AS CHAR));

END$$

DELIMITER ;
